"use strict";

module.exports = {
	rules: {
		"array-bracket-newline": ["error", { multiline: true }],
		"array-bracket-spacing": ["error", "never"],
		"array-element-newline": ["error", "consistent"],
		"block-spacing": ["error"],
		"brace-style": ["off"],
		camelcase: ["error"],
		"capitalized-comments": ["off"],
		"comma-dangle": ["error", "always"],
		"comma-spacing": ["error"],
		"comma-style": ["off"],
		"computed-property-spacing": ["off"],
		"consistent-this": ["off"],
		"eol-last": ["error", "always"],
		"func-call-spacing": ["off"],
		"func-name-matching": ["off"],
		"func-names": ["off"],
		"func-style": ["off"],
		"function-call-argument-newline": ["off"],
		"function-paren-newline": ["off"],
		"id-denylist": ["off"],
		"id-length": ["off"],
		"id-match": ["off"],
		"implicit-arrow-linebreak": ["off"],
		indent: ["off"],
		"jsx-quotes": ["off"],
		"key-spacing": ["off"],
		"keyword-spacing": ["off"],
		"line-comment-position": ["off"],
		"linebreak-style": ["off"],
		"lines-around-comment": ["off"],
		"lines-between-class-members": ["off"],
		"max-depth": ["off"],
		"max-len": ["off"],
		"max-lines": ["off"],
		"max-lines-per-function": ["off"],
		"max-nested-callbacks": ["off"],
		"max-params": ["off"],
		"max-statements": ["off"],
		"max-statements-per-line": ["off"],
		"multiline-comment-style": ["off"],
		"multiline-ternary": ["off"],
		"new-cap": ["error"],
		"new-parens": ["off"],
		"newline-per-chained-call": ["off"],
		"no-array-constructor": ["off"],
		"no-bitwise": ["off"],
		"no-continue": ["off"],
		"no-inline-comments": ["off"],
		"no-lonely-if": ["off"],
		"no-mixed-operators": ["off"],
		"no-mixed-spaces-and-tabs": ["off"],
		"no-multi-assign": ["error"],
		"no-multiple-empty-lines": ["off"],
		"no-negated-condition": ["off"],

		// disable in favor of unicorn/no-nested-ternary
		"no-nested-ternary": ["off"],
		"no-new-object": ["off"],
		"no-plusplus": ["off"],
		"no-restricted-syntax": ["off"],
		"no-tabs": ["off"],
		"no-ternary": ["off"],
		"no-trailing-spaces": ["off"],
		"no-underscore-dangle": ["off"],
		"no-unneeded-ternary": ["off"],
		"no-whitespace-before-property": ["off"],
		"nonblock-statement-body-position": ["off"],
		"object-curly-newline": ["off"],
		"object-curly-spacing": ["off"],
		"object-property-newline": ["off"],
		"one-var": ["error", { initialized: "never", uninitialized: "always" }],
		"one-var-declaration-per-line": ["off"],
		"operator-assignment": ["off"],
		"operator-linebreak": ["off"],
		"padded-blocks": ["off"],
		"padding-line-between-statements": ["off"],
		"prefer-exponentiation-operator": ["off"],
		"prefer-object-spread": ["off"],
		"quote-props": ["off"],
		quotes: ["off"],
		semi: ["off"],
		"semi-spacing": ["off"],
		"semi-style": ["off"],
		"sort-keys": ["error"],
		"sort-vars": ["off"],
		"space-before-blocks": ["off"],
		"space-before-function-paren": ["off"],
		"space-in-parens": ["off"],
		"space-infix-ops": ["off"],
		"space-unary-ops": ["off"],
		"spaced-comment": ["error"],
		"switch-colon-spacing": ["off"],
		"template-tag-spacing": ["off"],
		"unicode-bom": ["error", "never"],
		"wrap-regex": ["off"],
	},
};
